
jdk:
  - openjdk8
language: java
script:
  - "mvn clean"
  - "mvn evosuite:generate"
  - "mvn evosuite:export"
  - "mvn test"
  - "mvn jacoco:report"
  - "mvn coveralls:report"

after_success:
  - "mvn org.jacoco:jacoco-maven-plugin:prepare-agent coveralls:report"